export const sampleItems = [
  { name: 'Milk', amount: 1 },
  { name: 'Bread', amount: 1 },
  { name: 'Eggs', amount: 12 },
  { name: 'Apples', amount: 1 },
  { name: 'Bananas', amount: 6 },
  { name: 'Chicken', amount: 1 },
  { name: 'Rice', amount: 2 },
  { name: 'Cheese', amount: 200 },
  { name: 'Tomatoes', amount: 500 },
  { name: 'Lettuce', amount: 1 },
  { name: 'Pasta', amount: 500 },
  { name: 'Juice', amount: 1 },
  { name: 'Yogurt', amount: 4 },
  { name: 'Cereal', amount: 1 },
  { name: 'Butter', amount: 250 },
  { name: 'Carrots', amount: 1 },
  { name: 'Cucumbers', amount: 2 },
  { name: 'Fish', amount: 1 },
  { name: 'Onions', amount: 1 },
  { name: 'Garlic', amount: 3 },
];
